[package]
name = "raytracing-rs"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# https://crates.io/
[dependencies]
winit = "0.29"
wgpu = "0.18"
cgmath = "0.18"
